{
 "title": "Dash Infra",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Primeiro Atendimento (evolução últimos 12 meses)",
   "type": "barchart",
   "description": "Evolução do tempo médio do primeiro atendimento, nos últimos 12 meses",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  STR_TO_DATE(CONCAT(YEAR(gt.date_creation), '-', MONTH(gt.date_creation), '-01'), '%Y-%m-%d') AS time, -- Campo de data válido\r\n  DATE_FORMAT(gt.date_creation, '%M/%Y') AS mes_ano, -- Nome do mês + ano (string opcional)\r\n  AVG(gt.takeintoaccount_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Tempo Médio\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.date_creation >= DATE_SUB(NOW(), INTERVAL 11 MONTH)\r\n  AND gt.is_deleted = 0\r\n  AND gg.completename LIKE '%Infra%'\r\nGROUP BY \r\n  time, mes_ano\r\nORDER BY \r\n  time ASC;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Primeiro Atendimento",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  'InfraEstrutura' AS \"Departamento\",\r\n  -- AVG(gt.takeintoaccount_delay_stat) AS \"Tempo Médio\"\r\n  AVG(gt.takeintoaccount_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Tempo Médio\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  $__timeFilter(gt.date_creation)\r\n  AND gg.completename LIKE '%InfraEstrutura%'\r\n  AND gt.is_deleted = 0\r\nGROUP BY \r\n  \"Departamento\";\r\n"
    }
   ]
  },
  {
   "title": "Média por Grupo",
   "type": "barchart",
   "description": "Tempo de atendimento médio para os tickets solucionados na faixa de tempo selecionada, por Grupo",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  ROUND(AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation))) AS avg_delay_minutes,\r\n  gg.name    \r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n  JOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n  $__timeFilter(gt.solvedate)\r\n  -- gt.solve_delay_stat != 0\r\n  AND gg.completename LIKE '%InfraEstrutura%'\r\n  -- AND gt.id=80444\r\n  -- AND gt.id=80763\r\n  -- AND gt.id=80723\r\n  AND gt.is_deleted = 0\r\n  AND gg.name NOT LIKE '%Triagem%'\r\nGROUP BY \r\n  gg.id\r\nORDER BY\r\n  gg.name;\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Tickets Total",
   "type": "barchart",
   "description": "Filtra a quantidade de tickets criados no range de tempo informado de acordo com o status, separado por Departamento<br>\nEncerrado engloba Solucionados e Fechados<br>\nEm atendimento engloba Atribuídos e Planejados",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  'Total' AS status, COUNT(*) AS total\r\nFROM glpi_tickets gt\r\nLEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\nLEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n$__timeFilter(gt.date_creation) \r\nAND gg.completename LIKE '%InfraEstrutura%'\r\nAND gt.is_deleted = 0\r\n\r\nUNION ALL\r\n\r\nSELECT \r\n  'Novo' AS status, COUNT(*) AS total\r\nFROM glpi_tickets gt\r\nLEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\nLEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n$__timeFilter(gt.date_creation) \r\nAND gg.completename LIKE '%InfraEstrutura%'\r\nAND gt.status = 1\r\nAND gt.is_deleted = 0\r\n\r\nUNION ALL\r\n\r\nSELECT \r\n  'Atribuído' AS status, COUNT(*) AS total\r\nFROM glpi_tickets gt\r\nLEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\nLEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n$__timeFilter(gt.date_creation) \r\nAND gg.completename LIKE '%InfraEstrutura%'\r\nAND gt.status = 2\r\nAND gt.is_deleted = 0\r\n\r\nUNION ALL\r\n\r\nSELECT \r\n  'Planejado' AS status, COUNT(*) AS total\r\nFROM glpi_tickets gt\r\nLEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\nLEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n$__timeFilter(gt.date_creation) \r\nAND gg.completename LIKE '%InfraEstrutura%'\r\nAND gt.status = 3\r\nAND gt.is_deleted = 0\r\n\r\nUNION ALL\r\n\r\nSELECT \r\n  'Pendente' AS status, COUNT(*) AS total\r\nFROM glpi_tickets gt\r\nLEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\nLEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n$__timeFilter(gt.date_creation) \r\nAND gg.completename LIKE '%InfraEstrutura%'\r\nAND gt.status = 4\r\nAND gt.is_deleted = 0\r\n\r\nUNION ALL\r\n\r\nSELECT \r\n  'Solucionado' AS status, COUNT(*) AS total\r\nFROM glpi_tickets gt\r\nLEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\nLEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n$__timeFilter(gt.date_creation) \r\nAND gg.completename LIKE '%InfraEstrutura%'\r\nAND gt.status = 5\r\nAND gt.is_deleted = 0\r\n\r\nUNION ALL\r\n\r\nSELECT \r\n  'Fechado' AS status, COUNT(*) AS total\r\nFROM glpi_tickets gt\r\nLEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\nLEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n$__timeFilter(gt.date_creation) \r\nAND gg.completename LIKE '%InfraEstrutura%'\r\nAND gt.status = 6\r\nAND gt.is_deleted = 0\r\n"
    }
   ]
  },
  {
   "title": "SLA - Service Level Agreement",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  'Sistemas' AS \"Departamento\",\r\n  AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Tempo Médio\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  $__timeFilter(gt.date_creation)\r\n  AND gg.completename LIKE '%Sistemas%'\r\n  -- AND gt.id=80763\r\n  AND gt.is_deleted = 0\r\nGROUP BY \r\n  Departamento\r\nORDER BY \r\n  \"Tempo Médio\" DESC;\r\n"
    }
   ]
  },
  {
   "title": "Tickets por Grupos",
   "type": "barchart",
   "description": "Gráfico de barras com duas colunas sendo uma com a quantidade total de chamados abertos no dia, uma coluna com a quantidade de chamados por nível de atendimento (QTD de N1, QTD de N2 e QTD de N3) e uma terceira com a quantidade de chamados sem atendimento.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT\r\n\t-- COUNT(gt.id) as \"Total\",\r\n\t-- SUM(gt.status IN (1,2,3,4)) as \"Abertos\",\r\n\tSUM(gt.status = 1) as \"Novo\",\r\n  SUM(gt.status = 2) as \"Atribuído\",\r\n  SUM(gt.status = 3) as \"Planejado\",\r\n  SUM(gt.status = 4) as \"Pendente\",\r\n  SUM(gt.status = 5) as \"Solucionado\",  \r\n  SUM(gt.status = 6) as \"Fechado\",\r\n  gg.name\r\nFROM \r\n    glpi_tickets gt\r\n\tJOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n\tJOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n\t$__timeFilter(gt.date_creation)\r\n\tAND gg.completename LIKE '%InfraEstrutura%'\r\n\tAND gt.is_deleted = 0\r\nGROUP BY \r\n\tgg.id\r\nORDER BY\r\n\tgg.name"
    }
   ]
  },
  {
   "title": "Tickets com mais de 10 dias",
   "type": "table",
   "description": "Lista para auxiliar diretores avaliar tickets antigos",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  gt.id AS \"Ticket GLPI\",\r\n  gt.name AS \"Título\",\r\n  DATE_FORMAT(gt.date, '%d/%m/%Y') AS \"Criação\",\r\n  CASE \r\n    WHEN gt.status LIKE '1' THEN 'Novo'\r\n    WHEN gt.status LIKE '2' THEN 'Atribuído'\r\n    WHEN gt.status LIKE '3' THEN 'Planejado'\r\n    WHEN gt.status LIKE '4' THEN 'Pendente'\r\n    WHEN gt.status LIKE '5' THEN 'Solucionado'\r\n    WHEN gt.status LIKE '6' THEN 'Fechado'\r\n    ELSE \"Outro\"\r\n  END AS \"Status\",\r\n  -- CASE \r\n  --   WHEN gg.completename LIKE '%InfraEstrutura%' THEN 'InfraEstrutura'\r\n  --   WHEN gg.completename LIKE '%Sistemas%' THEN 'Sistemas'\r\n  --   WHEN gg.completename LIKE '%Suporte%' THEN 'Suporte'\r\n  --   WHEN gg.completename LIKE '%Pessoas%' THEN 'Gestão de Pessoas'\r\n  --   WHEN gg.completename LIKE '%Administração%' THEN 'Administração'\r\n  --   ELSE \"Outros\"\r\n  -- END AS \"Departamento\",\r\n  gg.name AS \"Grupo\",\r\n  GROUP_CONCAT(DISTINCT CONCAT(gu.firstname, ' ', gu.realname) SEPARATOR ', ') AS \"Responsáveis\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\n  JOIN glpi_tickets_users gtu ON gt.id = gtu.tickets_id\r\n  JOIN glpi_users gu ON gtu.users_id = gu.id\r\nWHERE \r\n  solvedate IS NULL\r\n  AND date < DATE_SUB(NOW(), INTERVAL 10 DAY)\r\n  AND gtu.type = 2\r\n  AND (gg.completename LIKE '%InfraEstrutura%')\r\n  AND gt.is_deleted = 0\r\nGROUP BY gt.id, gt.name, gt.date, gt.status, gg.completename\r\nORDER BY gt.date ASC\r\n"
    }
   ]
  },
  {
   "title": "Detalhes Tickets ",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  gt.id AS \"ID\",\r\n  -- gt.solve_delay_stat AS \"Tempo\",\r\n  gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation) as \"Tempo\",\r\n  gg.name AS \"Grupo\",\r\n  gt.date_creation AS \"Abertura\",\r\n  gt.solvedate AS \"Solucionado\"\r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n  JOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n  $__timeFilter(gt.solvedate)\r\n  -- gt.date_creation >= DATE_SUB(NOW(), INTERVAL 2 DAY)\r\n  -- gt.solve_delay_stat != 0\r\n  AND gg.completename LIKE '%Infra%'\r\n  AND gt.is_deleted = 0\r\nORDER BY\r\n  gt.solve_delay_stat DESC"
    }
   ]
  },
  {
   "title": "Tickets por Agente",
   "type": "table",
   "description": "Filtra chamados encerrados / média tempo / por agente no range de data especificado.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT\r\n  CONCAT(gu.firstname,' ',gu.realname) as \"Nome\",\r\n  COUNT(gt.id) as \"Tickets\",\r\n  AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) as \"Média\",\r\n  -- CASE \r\n  --   WHEN gg.completename LIKE '%InfraEstrutura%' THEN 'InfraEstrutura'\r\n  --   WHEN gg.completename LIKE '%Sistemas%' THEN 'Sistemas'\r\n  --   WHEN gg.completename LIKE '%Pessoas%' THEN 'Gestão de Pessoas'\r\n  --   WHEN gg.completename LIKE '%Administração%' THEN 'Administração'\r\n  --   ELSE 'Suporte'\r\n  -- END AS \"Departamento\",\r\n  gg.name as \"Setor\"\r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_tickets_users gtu ON gt.id = gtu.tickets_id\r\n  JOIN glpi_users gu ON gu.id = gtu.users_id\r\n  JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  $__timeFilter(gt.solvedate)\r\n  AND gtu.type=2\r\n  AND gg.completename LIKE '%InfraEstrutura%'\r\n  AND gt.is_deleted = 0\r\nGROUP BY \r\n  Nome\r\nORDER BY \r\n  -- Departamento DESC,\r\n  Setor ASC,\r\n  Tickets DESC"
    }
   ]
  }
 ]
}