{
 "title": "Dashboard Geral",
 "description": "estudos cck",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tickets com mais de 10 dias",
   "type": "table",
   "description": "Lista para auxiliar diretores avaliar tickets antigos",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  gt.id AS \"Ticket GLPI\",\r\n  gt.name AS \"Título\",\r\n  DATE_FORMAT(gt.date, '%d/%m/%Y') AS \"Criação\",\r\n  CASE \r\n    WHEN gt.status LIKE '1' THEN 'Novo'\r\n    WHEN gt.status LIKE '2' THEN 'Atribuído'\r\n    WHEN gt.status LIKE '3' THEN 'Planejado'\r\n    WHEN gt.status LIKE '4' THEN 'Pendente'\r\n    WHEN gt.status LIKE '5' THEN 'Solucionado'\r\n    WHEN gt.status LIKE '6' THEN 'Fechado'\r\n    ELSE \"Outro\"\r\n  END AS \"Status\",\r\n  CASE \r\n    WHEN gg.completename LIKE '%InfraEstrutura%' THEN 'InfraEstrutura'\r\n    WHEN gg.completename LIKE '%Sistemas%' THEN 'Sistemas'\r\n    WHEN gg.completename LIKE '%Suporte%' THEN 'Suporte'\r\n    WHEN gg.completename LIKE '%Pessoas%' THEN 'Gestão de Pessoas'\r\n    WHEN gg.completename LIKE '%Administração%' THEN 'Administração'\r\n    ELSE \"Outros\"\r\n  END AS \"Departamento\",\r\n  gg.name AS \"Grupo\",\r\n  GROUP_CONCAT(DISTINCT CONCAT(gu.firstname, ' ', gu.realname) SEPARATOR ', ') AS \"Responsáveis\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\n  JOIN glpi_tickets_users gtu ON gt.id = gtu.tickets_id\r\n  JOIN glpi_users gu ON gtu.users_id = gu.id\r\nWHERE \r\n  solvedate IS NULL\r\n  AND date < DATE_SUB(NOW(), INTERVAL 10 DAY)\r\n  AND gtu.type = 2\r\n  AND gt.is_deleted = 0\r\n  AND (gg.completename LIKE '%InfraEstrutura%' OR gg.completename LIKE '%Sistemas%' OR gg.completename LIKE '%Suporte%')\r\nGROUP BY gt.id, gt.name, gt.date, gt.status, gg.completename\r\nORDER BY gt.date ASC\r\n"
    }
   ]
  },
  {
   "title": "Tickets Status",
   "type": "barchart",
   "description": "Filtra a quantidade de tickets criados no range de tempo informado de acordo com o status.<br>\nEncerrado engloba Solucionados e Fechados<br>\nEm atendimento engloba Atribuídos e Planejados",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  DATE_FORMAT(gt.date_creation, '%d/%m/%Y') as \"Data\",\r\n  COUNT(gt.id) as \"Total\",\r\n  SUM(gt.status IN (5,6)) as \"Encerrado\",\r\n  SUM(gt.status IN (2,3)) as \"Em Atendimento\",\r\n  SUM(gt.status = 1) as \"Novo\",\r\n  SUM(gt.status = 4) as \"Pendente\"\r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n\tJOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n  $__timeFilter(gt.date_creation)\r\n  AND gt.is_deleted = 0\r\n  AND (gg.completename LIKE '%Suporte%' OR gg.completename LIKE '%Infra%' OR gg.completename LIKE '%Sistemas%')\r\nGROUP BY \r\n  DATE_FORMAT(gt.date_creation, '%d/%m/%Y')\r\nORDER BY \r\n  gt.date_creation;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Tickets Não Resolvidos",
   "type": "barchart",
   "description": "Filtra tickets criados no range de tempo informado que estão com status diferente de Solucionado ou Fechado",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  DATE_FORMAT(gt.date_creation, '%d/%m/%Y') as \"Data\",\r\n  COUNT(gt.id) as \"Total de Tickets\"\r\nFROM \r\n  glpi_tickets gt\r\nWHERE \r\n  $__timeFilter(gt.date_creation)\r\n  AND gt.status != 6\r\n  AND gt.status != 5\r\n  AND gt.is_deleted = 0\r\nGROUP BY \r\n  Data\r\nORDER BY \r\n  gt.date_creation ASC;\r\n"
    }
   ]
  },
  {
   "title": "Tickets por Secretaria",
   "type": "table",
   "description": "Filtra a quantidade de tickets criados no range de tempo informado, separado por Secretaria solicitante.",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 37 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n-- gl.completename as \"Unidade\",\r\n  CASE \r\n    WHEN gl.completename LIKE '%SMAS%' THEN 'SMAS'\r\n    WHEN gl.completename LIKE '%SMED%' THEN 'SMED'\r\n    WHEN gl.completename LIKE '%SMCIT%' THEN 'SMCIT'\r\n    WHEN gl.completename LIKE '%SMSA%' THEN 'SMSA'\r\n    WHEN gl.completename LIKE '%SMPL%' THEN 'SMPL'\r\n    WHEN gl.completename LIKE '%PGM%' THEN 'PGM'\r\n    WHEN gl.completename LIKE '%SMEL%' THEN 'SMEL'\r\n    WHEN gl.completename LIKE '%SMMA%' THEN 'SMMA'  \r\n    WHEN gl.completename LIKE '%SMAD%' THEN 'SMAD'    \r\n    WHEN gl.completename LIKE '%SMAG%' THEN 'SMAG'    \r\n    WHEN gl.completename LIKE '%SMCS%' THEN 'SMCS'\r\n    WHEN gl.completename LIKE '%SMCT%' THEN 'SMCT'\r\n    WHEN gl.completename LIKE '%SMFI%' THEN 'SMFI'\r\n    WHEN gl.completename LIKE '%SMGO%' THEN 'SMGO'\r\n    WHEN gl.completename LIKE '%SMOP%' THEN 'SMOP'\r\n    WHEN gl.completename LIKE '%SMSP%' THEN 'SMSP'\r\n    WHEN gl.completename LIKE '%SMTE%' THEN 'SMTE'\r\n    WHEN gl.completename LIKE '%SMUR%' THEN 'SMUR'\r\n    WHEN gl.completename LIKE '%CGM%' THEN 'CGM'\r\n    WHEN gl.completename LIKE '%SMGP%' THEN 'SMGP'\r\n    ELSE \"Outros\"\r\n  END AS \"Unidade\",\r\n  COUNT(gt.id) as \"Total de Tickets\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_locations gl ON gt.locations_id = gl.id\r\nWHERE \r\n  $__timeFilter(gt.date_creation)\r\n  AND gt.is_deleted = 0\r\nGROUP BY \r\n  Unidade\r\nORDER BY \r\n  \"Total de Tickets\" DESC;"
    }
   ]
  },
  {
   "title": "Tickets Departamento",
   "type": "barchart",
   "description": "Filtra a quantidade de tickets criados no range de tempo informado de acordo com o status, separado por Departamento<br>\nEncerrado engloba Solucionados e Fechados<br>\nEm atendimento engloba Atribuídos e Planejados",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 37 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  CASE \r\n    WHEN gg.completename LIKE '%InfraEstrutura%' THEN 'InfraEstrutura'\r\n    WHEN gg.completename LIKE '%Sistemas%' THEN 'Sistemas'\r\n    WHEN gg.completename LIKE '%Suporte%' THEN 'Suporte'\r\n    WHEN gg.completename LIKE '%Pessoas%' THEN 'Gestão de Pessoas'\r\n    WHEN gg.completename LIKE '%Administração%' THEN 'Administração'\r\n    ELSE \"Outros\"\r\n  END AS \"Departamento\",\r\n  COUNT(gt.id) as \"Total\",\r\n  SUM(gt.status IN (5,6)) as \"Encerrado\",\r\n  SUM(gt.status IN (2,3)) as \"Em Atendimento\",\r\n  SUM(gt.status = 1) as \"Novo\",\r\n  SUM(gt.status = 4) as \"Pendente\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  $__timeFilter(gt.date_creation)\r\n  AND gt.is_deleted = 0\r\n  AND (gg.completename LIKE '%Suporte%' OR gg.completename LIKE '%Infra%' OR gg.completename LIKE '%Sistemas%')\r\nGROUP BY \r\n  Departamento\r\nORDER BY \r\n  Departamento;\r\n"
    }
   ]
  },
  {
   "title": "Tickets Abertos GERAL por Grupo",
   "type": "barchart",
   "description": "Tickets com status diferente de Solucionado ou Fechado em tempo real, dividido por Grupos",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT\r\n  COUNT(*),\r\n  gg.name,\r\n\tSUBSTRING_INDEX(gg.name, '-', 1)    \r\nFROM \r\n    glpi_tickets gt\r\n\tJOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n\tJOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n\tgt.status != 6\r\n\tAND gt.status != 5\r\n  AND gt.is_deleted = 0\r\n\tAND gg.name NOT LIKE '%Triagem%'\r\n\tAND (gg.completename LIKE '%Suporte%' OR gg.completename LIKE '%Infra%' OR gg.completename LIKE '%Sistemas%')\r\nGROUP BY \r\n\tgg.id\r\nORDER BY\r\n\tgg.name"
    }
   ]
  },
  {
   "title": "Média GERAL por Grupo",
   "type": "barchart",
   "description": "Tempo de atendimento médio para os tickets solucionados na faixa de tempo selecionada, por Grupo",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  -- ROUND(AVG(gt.solve_delay_stat)) AS avg_delay_minutes, \r\n  ROUND(AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation))) AS avg_delay_minutes, \r\n  gg.name    \r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n  JOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n  $__timeFilter(gt.solvedate)\r\n  AND gt.is_deleted = 0\r\n  AND (gg.completename LIKE '%Suporte%' OR gg.completename LIKE '%Infra%' OR gg.completename LIKE '%Sistemas%')\r\nGROUP BY \r\n  gg.id\r\nORDER BY\r\n  gg.name;\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Tempo Médio Atendimento",
   "type": "barchart",
   "description": "Tempo de atendimento médio para os tickets solucionados na faixa de tempo selecionada, por Departamento",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  CASE \r\n    WHEN gg.completename LIKE '%InfraEstrutura%' THEN 'InfraEstrutura'\r\n    WHEN gg.completename LIKE '%Sistemas%' THEN 'Sistemas'\r\n    WHEN gg.completename LIKE '%Suporte%' THEN 'Suporte'\r\n    WHEN gg.completename LIKE '%Pessoas%' THEN 'Gestão de Pessoas'\r\n    WHEN gg.completename LIKE '%Administração%' THEN 'Administração'\r\n    ELSE 'Outros'\r\n  END AS \"Departamento\",\r\n  -- AVG(gt.solve_delay_stat) AS \"Tempo Médio\"\r\n  AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Tempo Médio\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  $__timeFilter(gt.solvedate)\r\n  AND gt.is_deleted = 0\r\n  AND (gg.completename LIKE '%Suporte%' OR gg.completename LIKE '%Infra%' OR gg.completename LIKE '%Sistemas%')\r\nGROUP BY \r\n  Departamento\r\nORDER BY \r\n  \"Tempo Médio\" DESC;\r\n"
    }
   ]
  },
  {
   "title": "Primeira Resposta (média)",
   "type": "barchart",
   "description": "Tempo médio da primeira resposta para os tickets criados na faixa de tempo selecionada, por Departamento",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  CASE \r\n    WHEN gg.completename LIKE '%InfraEstrutura%' THEN 'InfraEstrutura'\r\n    WHEN gg.completename LIKE '%Sistemas%' THEN 'Sistemas'\r\n    WHEN gg.completename LIKE '%Suporte%' THEN 'Suporte'\r\n    WHEN gg.completename LIKE '%Pessoas%' THEN 'Gestão de Pessoas'\r\n    WHEN gg.completename LIKE '%Administração%' THEN 'Administração'\r\n    ELSE 'Outro'\r\n  END AS \"Departamento\",\r\n  -- AVG(gt.takeintoaccount_delay_stat - EXTRACT(EPOCH FROM (gt.date - gt.date_creation))) AS \"Tempo Médio\" (Postgres)\r\n  AVG(gt.takeintoaccount_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Tempo Médio\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  $__timeFilter(gt.date_creation)\r\n  AND gt.is_deleted = 0\r\n  AND (gg.completename LIKE '%Suporte%' OR gg.completename LIKE '%Infra%' OR gg.completename LIKE '%Sistemas%')\r\nGROUP BY \r\n  Departamento\r\nORDER BY \r\n  \"Tempo Médio\" DESC;"
    }
   ]
  },
  {
   "title": "Primeiro Atendimento (evolução últimos 12 meses)",
   "type": "barchart",
   "description": "Evolução do tempo médio do primeiro atendimento, nos últimos 12 meses",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  STR_TO_DATE(CONCAT(YEAR(gt.date_creation), '-', MONTH(gt.date_creation), '-01'), '%Y-%m-%d') AS time, -- Campo de data válido\r\n  DATE_FORMAT(gt.date_creation, '%M/%Y') AS mes_ano, -- Nome do mês + ano (string opcional)\r\n  AVG(gt.takeintoaccount_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Tempo Médio\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.date_creation >= DATE_SUB(NOW(), INTERVAL 11 MONTH)\r\n  AND gt.is_deleted = 0\r\n  AND (gg.completename LIKE '%Infra%' OR gg.completename LIKE '%Suporte%' OR gg.completename LIKE '%Sistemas%')\r\nGROUP BY \r\n  time, mes_ano\r\nORDER BY \r\n  time ASC;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Projetos por Agente",
   "type": "table",
   "description": "Filtra projetos abertos por responsável",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 113 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT\r\n  gp.id as \"GLPI\",\r\n  gp.name as \"Projeto\",\r\n  CONCAT(gu.firstname, ' ', gu.realname) as \"Responsável\",\r\n  gp.priority as \"Prioridade\",\r\n  gp.percent_done as \"Concluído\",\r\n  gps.name as \"Status\",\r\n  DATE_FORMAT(gp.date_creation, '%d/%m/%Y') as \"Abertura\",\r\n  DATE_FORMAT(gp.plan_end_date, '%d/%m/%Y') as \"Encerramento (estimado)\"\r\nFROM \r\n  glpi_projects gp\r\nLEFT JOIN glpi_users gu ON gp.users_id = gu.id\r\nLEFT JOIN glpi_projectstates gps ON gps.id = gp.projectstates_id\r\nWHERE \r\n  gp.is_deleted = 0\r\n  AND gps.name != 'Closed'\r\n  AND gp.is_template = 0\r\nORDER BY gp.date_creation ASC;\r\n"
    }
   ]
  },
  {
   "title": "Tickets Solucionados por Agente",
   "type": "table",
   "description": "Filtra chamados encerrados / média tempo / por agente no range de data especificado.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 125 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT\r\n  CONCAT(gu.firstname,' ',gu.realname) as \"Nome\",\r\n  COUNT(gt.id) as \"Tickets\",\r\n  -- AVG(gt.solve_delay_stat) as \"Média\",\r\n  AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Média\",\r\n    CASE \r\n    WHEN gg.completename LIKE '%InfraEstrutura%' THEN 'InfraEstrutura'\r\n    WHEN gg.completename LIKE '%Sistemas%' THEN 'Sistemas'\r\n    WHEN gg.completename LIKE '%Suporte%' THEN 'Suporte'\r\n    WHEN gg.completename LIKE '%Pessoas%' THEN 'Gestão de Pessoas'\r\n    WHEN gg.completename LIKE '%Administração%' THEN 'Administração'\r\n    ELSE 'Outros'\r\n  END AS \"Departamento\",\r\n  gg.name as \"Setor\"\r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_tickets_users gtu ON gt.id = gtu.tickets_id\r\n  JOIN glpi_users gu ON gu.id = gtu.users_id\r\n  JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  $__timeFilter(gt.solvedate)\r\n  AND gtu.type = 2\r\n  AND gt.is_deleted = 0\r\nGROUP BY \r\n  Nome\r\nORDER BY \r\n  Departamento DESC,\r\n  Setor ASC,\r\n  Tickets DESC"
    }
   ]
  },
  {
   "title": "Tickets Total por Agente",
   "type": "table",
   "description": "Filtra chamados encerrados / média tempo / por agente no range de data especificado.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 133 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT\r\n  CONCAT(gu.firstname,' ',gu.realname) as \"Nome\",\r\n  COUNT(gt.id) as \"Tickets Total\",\r\n  COUNT(gt.solvedate) as \"Tickets Solucionados\",\r\n  -- AVG(gt.solve_delay_stat) as \"Média\",\r\n  AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Média\",\r\n    CASE \r\n    WHEN gg.completename LIKE '%InfraEstrutura%' THEN 'InfraEstrutura'\r\n    WHEN gg.completename LIKE '%Sistemas%' THEN 'Sistemas'\r\n    WHEN gg.completename LIKE '%Suporte%' THEN 'Suporte'\r\n    WHEN gg.completename LIKE '%Pessoas%' THEN 'Gestão de Pessoas'\r\n    WHEN gg.completename LIKE '%Administração%' THEN 'Administração'\r\n    ELSE 'Outros'\r\n  END AS \"Departamento\",\r\n  gg.name as \"Setor\"\r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_tickets_users gtu ON gt.id = gtu.tickets_id\r\n  JOIN glpi_users gu ON gu.id = gtu.users_id\r\n  JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  $__timeFilter(gt.date)\r\n  AND gtu.type = 2\r\n  AND gt.is_deleted = 0\r\nGROUP BY \r\n  Nome\r\nORDER BY \r\n  Departamento DESC,\r\n  Setor ASC"
    }
   ]
  },
  {
   "title": "Suporte",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 },
   "collapsed": true,
   "panels": [
    {
     "title": "Média SUPORTE por Grupo",
     "type": "barchart",
     "description": "Tempo de atendimento médio para os tickets solucionados na faixa de tempo selecionada, por Grupo",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 180 },
     "fieldConfig": { "defaults": { "unit": "clocks" } },
     "targets": [
      {
       "dataset": "glpi_db",
       "rawSql": "SELECT \r\n  -- ROUND(AVG(gt.solve_delay_stat)) AS avg_delay_minutes, \r\n  ROUND(AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation))) AS avg_delay_minutes, \r\n  gg.name    \r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n  JOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n  $__timeFilter(gt.solvedate)\r\n  -- gt.solve_delay_stat != 0\r\n  AND gg.completename LIKE '%Suporte%'\r\n  -- AND gt.id=80444\r\n  -- AND gt.id=80763\r\n  -- AND gt.id=80723\r\n  AND gt.is_deleted = 0  \r\nGROUP BY \r\n  gg.id\r\nORDER BY\r\n  gg.name;\r\n\r\n\r\n"
      }
     ]
    },
    {
     "title": "Tickets Abertos SUPORTE por Grupo",
     "type": "barchart",
     "description": "Tickets com status diferente de Solucionado ou Fechado em tempo real, dividido por Grupos",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 242 },
     "targets": [
      {
       "dataset": "glpi_db",
       "rawSql": "SELECT\r\n  COUNT(*),\r\n  gg.name,\r\n\tSUBSTRING_INDEX(gg.name, '-', 1)    \r\nFROM \r\n    glpi_tickets gt\r\n\tJOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n\tJOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n\tgt.status != 6\r\n\tAND gt.status != 5\r\n\t-- AND gr.name LIKE '%Nivel % - Infra'\r\n\tAND gg.completename LIKE '%Suporte%'\r\n  AND gt.is_deleted = 0\t\r\nGROUP BY \r\n\tgg.id\r\nORDER BY\r\n\tgg.name"
      }
     ]
    },
    {
     "title": "Tickets SUPORTE por Grupos",
     "type": "barchart",
     "description": "Gráfico de barras com duas colunas sendo uma com a quantidade total de chamados abertos no dia, uma coluna com a quantidade de chamados por nível de atendimento (QTD de N1, QTD de N2 e QTD de N3) e uma terceira com a quantidade de chamados sem atendimento.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 253 },
     "targets": [
      {
       "dataset": "glpi_db",
       "rawSql": "SELECT\r\n\tCOUNT(gt.id) as \"Total\",\r\n\tSUM(gt.status IN (1,2,3,4)) as \"Abertos\",\r\n  gg.name,\r\n\tSUBSTRING_INDEX(gg.name, '-', 1)    \r\nFROM \r\n    glpi_tickets gt\r\n\tJOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n\tJOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n\t$__timeFilter(gt.date_creation)\r\n\tAND gg.completename LIKE '%Suporte%'\r\n  AND gt.is_deleted = 0\t\r\nGROUP BY \r\n\tgg.id\r\nORDER BY\r\n\tgg.name"
      }
     ]
    },
    {
     "title": "Tickets SUPORTE por Agente",
     "type": "table",
     "description": "Filtra chamados encerrados / média tempo / por agente no range de data especificado.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 263 },
     "targets": [
      {
       "dataset": "glpi_db",
       "rawSql": "SELECT\r\n  CONCAT(gu.firstname,' ',gu.realname) as \"Nome\",\r\n  COUNT(gt.id) as \"Tickets\",\r\n  -- AVG(gt.solve_delay_stat) as \"Média\",\r\n  AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Média\",\r\n  gg.name as \"Setor\"\r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_tickets_users gtu ON gt.id = gtu.tickets_id\r\n  JOIN glpi_users gu ON gu.id = gtu.users_id\r\n  JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  $__timeFilter(gt.solvedate)\r\n  AND gtu.type=2\r\n  AND gg.completename LIKE '%Suporte%'\r\n  AND gt.is_deleted = 0  \r\nGROUP BY \r\n  Nome\r\nORDER BY \r\n  Setor ASC,\r\n  Tickets DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "Sistemas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 },
   "collapsed": true,
   "panels": [
    {
     "title": "Média SISTEMAS por Grupo",
     "type": "barchart",
     "description": "Tempo de atendimento médio para os tickets solucionados na faixa de tempo selecionada, por Grupo",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "clocks" } },
     "targets": [
      {
       "dataset": "glpi_db",
       "rawSql": "SELECT \r\n  -- ROUND(AVG(gt.solve_delay_stat)) AS avg_delay_minutes, \r\n  ROUND(AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation))) AS avg_delay_minutes,\r\n  gg.name    \r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n  JOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n  $__timeFilter(gt.solvedate)\r\n  -- gt.solve_delay_stat != 0\r\n  AND gg.completename LIKE '%Sistemas%'\r\n  -- AND gt.id=80444\r\n  -- AND gt.id=80763\r\n  -- AND gt.id=80723\r\n  AND gt.is_deleted = 0  \r\nGROUP BY \r\n  gg.id\r\nORDER BY\r\n  gg.name;\r\n\r\n\r\n"
      }
     ]
    },
    {
     "title": "Tickets Abertos SISTEMAS por Grupo",
     "type": "barchart",
     "description": "Tickets com status diferente de Solucionado ou Fechado em tempo real, dividido por Grupos",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 243 },
     "targets": [
      {
       "dataset": "glpi_db",
       "rawSql": "SELECT\r\n  COUNT(*),\r\n  gg.name,\r\n\tSUBSTRING_INDEX(gg.name, '-', 1)    \r\nFROM \r\n    glpi_tickets gt\r\n\tJOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n\tJOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n\tgt.status != 6\r\n\tAND gt.status != 5\r\n\t-- AND gr.name LIKE '%Nivel % - Infra'\r\n\tAND gg.completename LIKE '%Sistemas%'\r\n  AND gt.is_deleted = 0\t\r\nGROUP BY \r\n\tgg.id\r\nORDER BY\r\n\tgg.name"
      }
     ]
    },
    {
     "title": "Tickets SISTEMAS por Grupos",
     "type": "barchart",
     "description": "Gráfico de barras com duas colunas sendo uma com a quantidade total de chamados abertos no dia, uma coluna com a quantidade de chamados por nível de atendimento (QTD de N1, QTD de N2 e QTD de N3) e uma terceira com a quantidade de chamados sem atendimento.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 255 },
     "targets": [
      {
       "dataset": "glpi_db",
       "rawSql": "SELECT\r\n\tCOUNT(gt.id) as \"Total\",\r\n\tSUM(gt.status IN (1,2,3,4)) as \"Abertos\",\r\n  gg.name,\r\n\tSUBSTRING_INDEX(gg.name, '-', 1)    \r\nFROM \r\n    glpi_tickets gt\r\n\tJOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n\tJOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n\t$__timeFilter(gt.date_creation)\r\n\tAND gg.completename LIKE '%Sistemas%'\r\n  AND gt.is_deleted = 0\t\r\nGROUP BY \r\n\tgg.id\r\nORDER BY\r\n\tgg.name"
      }
     ]
    },
    {
     "title": "Tickets SISTEMAS por Agente",
     "type": "table",
     "description": "Filtra chamados encerrados / média tempo / por agente no range de data especificado.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 266 },
     "targets": [
      {
       "dataset": "glpi_db",
       "rawSql": "SELECT\r\n  CONCAT(gu.firstname,' ',gu.realname) as \"Nome\",\r\n  COUNT(gt.id) as \"Tickets\",\r\n  AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) as \"Média\",\r\n  gg.name as \"Setor\"\r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_tickets_users gtu ON gt.id = gtu.tickets_id\r\n  JOIN glpi_users gu ON gu.id = gtu.users_id\r\n  JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  $__timeFilter(gt.solvedate)\r\n  AND gtu.type=2\r\n  AND gg.completename LIKE '%Sistemas%'\r\n  AND gt.is_deleted = 0  \r\nGROUP BY \r\n  Nome\r\nORDER BY \r\n  Setor ASC,\r\n  Tickets DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "InfraEstrutura",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 },
   "collapsed": true,
   "panels": [
    {
     "title": "Média INFRA por Grupo",
     "type": "barchart",
     "description": "Tempo de atendimento médio para os tickets solucionados na faixa de tempo selecionada, por Grupo",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 182 },
     "fieldConfig": { "defaults": { "unit": "clocks" } },
     "targets": [
      {
       "dataset": "glpi_db",
       "rawSql": "SELECT \r\n  -- ROUND(AVG(gt.solve_delay_stat)) AS avg_delay_minutes,\r\n  ROUND(AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation))) AS avg_delay_minutes,\r\n  gg.name    \r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n  JOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n  $__timeFilter(gt.solvedate)\r\n  -- gt.solve_delay_stat != 0\r\n  AND gg.completename LIKE '%InfraEstrutura%'\r\n  -- AND gt.id=80444\r\n  -- AND gt.id=80763\r\n  -- AND gt.id=80723\r\n  AND gt.is_deleted = 0  \r\nGROUP BY \r\n  gg.id\r\nORDER BY\r\n  gg.name;\r\n\r\n\r\n"
      }
     ]
    },
    {
     "title": "Tickets Abertos INFRA por Grupo",
     "type": "barchart",
     "description": "Tickets com status diferente de Solucionado ou Fechado em tempo real, dividido por Grupos",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 199 },
     "targets": [
      {
       "dataset": "glpi_db",
       "rawSql": "SELECT\r\n  COUNT(*),\r\n  gg.name,\r\n\tSUBSTRING_INDEX(gg.name, '-', 1)    \r\nFROM \r\n    glpi_tickets gt\r\n\tJOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n\tJOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n\tgt.status != 6\r\n\tAND gt.status != 5\r\n\t-- AND gr.name LIKE '%Nivel % - Infra'\r\n\tAND gg.completename LIKE '%InfraEstrutura%'\r\n  AND gt.is_deleted = 0\t\r\nGROUP BY \r\n\tgg.id\r\nORDER BY\r\n\tgg.name"
      }
     ]
    },
    {
     "title": "Tickets INFRA por Grupos",
     "type": "barchart",
     "description": "Gráfico de barras com duas colunas sendo uma com a quantidade total de chamados abertos no dia, uma coluna com a quantidade de chamados por nível de atendimento (QTD de N1, QTD de N2 e QTD de N3) e uma terceira com a quantidade de chamados sem atendimento.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 211 },
     "targets": [
      {
       "dataset": "glpi_db",
       "rawSql": "SELECT\r\n\tCOUNT(gt.id) as \"Total\",\r\n\tSUM(gt.status IN (1,2,3,4)) as \"Abertos\",\r\n  gg.name,\r\n\tSUBSTRING_INDEX(gg.name, '-', 1)    \r\nFROM \r\n    glpi_tickets gt\r\n\tJOIN glpi_groups_tickets ggt ON gt.id = ggt.tickets_id\r\n\tJOIN glpi_groups gg ON gg.id = ggt.groups_id\r\nWHERE \r\n\t$__timeFilter(gt.date_creation)\r\n\tAND gg.completename LIKE '%InfraEstrutura%'\r\n  AND gt.is_deleted = 0\t\r\nGROUP BY \r\n\tgg.id\r\nORDER BY\r\n\tgg.name"
      }
     ]
    },
    {
     "title": "Tickets INFRA por Agente",
     "type": "table",
     "description": "Filtra chamados encerrados / média tempo / por agente no range de data especificado.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 220 },
     "targets": [
      {
       "dataset": "glpi_db",
       "rawSql": "SELECT\r\n  CONCAT(gu.firstname,' ',gu.realname) as \"Nome\",\r\n  COUNT(gt.id) as \"Tickets\",\r\n  AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) as \"Média\",\r\n  gg.name as \"Setor\"\r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_tickets_users gtu ON gt.id = gtu.tickets_id\r\n  JOIN glpi_users gu ON gu.id = gtu.users_id\r\n  JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  $__timeFilter(gt.solvedate)\r\n  AND gtu.type=2\r\n  AND gg.completename LIKE '%InfraEstrutura%'\r\n  AND gt.is_deleted = 0  \r\nGROUP BY \r\n  Nome\r\nORDER BY \r\n  Setor ASC,\r\n  Tickets DESC"
      }
     ]
    }
   ]
  }
 ]
}