{
 "title": "Painel da Gestão Diária",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "SLA 1ª Resposta Geral (24 h)",
   "type": "gauge",
   "description": "Tempo médio para a primeira resposta ao ticket, nas últimas 24 horas",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  AVG(gt.takeintoaccount_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Tempo Médio\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.date_creation >= DATE_SUB(NOW(), INTERVAL 24 HOUR)\r\n  AND (gg.completename LIKE '%Suporte%' OR gg.completename LIKE '%Infra%' OR gg.completename LIKE '%Sistemas%')\r\n  AND gt.is_deleted = 0\r\n"
    }
   ]
  },
  {
   "title": "Tempo Médio Atendimento Geral (24 h)",
   "type": "gauge",
   "description": "Tempo médio de atendimento dos tickets encerrados nas últimas 24h.",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Tempo Médio\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.solvedate >= DATE_SUB(NOW(), INTERVAL 24 HOUR)\r\n  AND (gg.completename LIKE '%Suporte%' OR gg.completename LIKE '%Infra%' OR gg.completename LIKE '%Sistemas%')\r\n  AND gt.is_deleted = 0\r\nORDER BY \r\n  \"Tempo Médio\" DESC;\r\n"
    }
   ]
  },
  {
   "title": "Tickets por Departamento (24 h)",
   "type": "barchart",
   "description": "Filtra os tickets criados nas últimas 24 horas, de acordo com o status, separado por Departamento<br>\nEncerrado engloba Solucionados e Fechados<br>\nEm atendimento engloba Atribuídos e Planejados",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  CASE \r\n    WHEN gg.completename LIKE '%InfraEstrutura%' THEN 'InfraEstrutura'\r\n    WHEN gg.completename LIKE '%Sistemas%' THEN 'Sistemas'\r\n    WHEN gg.completename LIKE '%Suporte%' THEN 'Suporte'\r\n    WHEN gg.completename LIKE '%Pessoas%' THEN 'Gestão de Pessoas'\r\n    WHEN gg.completename LIKE '%Administração%' THEN 'Administração'\r\n    ELSE \"Outros\"\r\n  END AS \"Departamento\",\r\n  COUNT(gt.id) as \"Total\",\r\n  SUM(gt.status IN (5,6)) as \"Encerrado\",\r\n  SUM(gt.status IN (2,3)) as \"Em Atendimento\",\r\n  SUM(gt.status = 1) as \"Novo\",\r\n  SUM(gt.status = 4) as \"Pendente\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.date_creation >= DATE_SUB(NOW(), INTERVAL 24 HOUR)\r\n  AND gt.is_deleted = 0\r\n  AND (gg.completename LIKE '%Suporte%' OR gg.completename LIKE '%Infra%' OR gg.completename LIKE '%Sistemas%')\r\nGROUP BY \r\n  Departamento\r\nORDER BY \r\n  Departamento;\r\n"
    }
   ]
  },
  {
   "title": "SLA 1ª Resposta Infra (24 h)",
   "type": "gauge",
   "description": "Tempo médio para a primeira resposta ao ticket, nas últimas 24 horas",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  AVG(gt.takeintoaccount_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Tempo Médio\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.date_creation >= DATE_SUB(NOW(), INTERVAL 24 HOUR)\r\n  AND gg.completename LIKE '%Infra%'\r\n  AND gt.is_deleted = 0\r\n"
    }
   ]
  },
  {
   "title": "Tempo Médio Atendimento Infra (24 h)",
   "type": "gauge",
   "description": "Tempo médio de atendimento dos tickets encerrados nas últimas 24h.",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Tempo Médio\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.solvedate >= DATE_SUB(NOW(), INTERVAL 24 HOUR)\r\n  AND gg.completename LIKE '%Infra%'\r\n  AND gt.is_deleted = 0\r\nORDER BY \r\n  \"Tempo Médio\" DESC;\r\n"
    }
   ]
  },
  {
   "title": "Tickets Infra (24 h)",
   "type": "barchart",
   "description": "Filtra os tickets criados nas últimas 24 horas, de acordo com o status<br>\nEncerrado engloba Solucionados e Fechados<br>\nEm atendimento engloba Atribuídos e Planejados",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  DATE_FORMAT(gt.date_creation, '%d/%m %H:00') as \"Hora\",\r\n  COUNT(gt.id) as \"Total\",\r\n  SUM(CASE WHEN gt.status IN (5,6) THEN 1 ELSE 0 END) as \"Encerrado\",\r\n  SUM(CASE WHEN gt.status IN (2,3) THEN 1 ELSE 0 END) as \"Em Atendimento\",\r\n  SUM(CASE WHEN gt.status = 1 THEN 1 ELSE 0 END) as \"Novo\",\r\n  SUM(CASE WHEN gt.status = 4 THEN 1 ELSE 0 END) as \"Pendente\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.date_creation >= DATE_SUB(NOW(), INTERVAL 24 HOUR) \r\n  AND gt.is_deleted = 0\r\n  AND gg.completename LIKE '%Infra%'  \r\nGROUP BY Hora\r\nORDER BY Hora ASC;\r\n"
    }
   ]
  },
  {
   "title": "Tickets Sistemas (24 h)",
   "type": "barchart",
   "description": "Filtra os tickets criados nas últimas 24 horas, de acordo com o status<br>\nEncerrado engloba Solucionados e Fechados<br>\nEm atendimento engloba Atribuídos e Planejados",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  DATE_FORMAT(gt.date_creation, '%d/%m %H:00') as \"Hora\",\r\n  COUNT(gt.id) as \"Total\",\r\n  SUM(CASE WHEN gt.status IN (5,6) THEN 1 ELSE 0 END) as \"Encerrado\",\r\n  SUM(CASE WHEN gt.status IN (2,3) THEN 1 ELSE 0 END) as \"Em Atendimento\",\r\n  SUM(CASE WHEN gt.status = 1 THEN 1 ELSE 0 END) as \"Novo\",\r\n  SUM(CASE WHEN gt.status = 4 THEN 1 ELSE 0 END) as \"Pendente\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.date_creation >= DATE_SUB(NOW(), INTERVAL 24 HOUR) \r\n  AND gt.is_deleted = 0\r\n  AND gg.completename LIKE '%Sistemas%'  \r\nGROUP BY Hora\r\nORDER BY Hora ASC;\r\n"
    }
   ]
  },
  {
   "title": "Tickets Suporte (24 h)",
   "type": "barchart",
   "description": "Filtra os tickets criados nas últimas 24 horas, de acordo com o status, separado por Departamento<br>\nEncerrado engloba Solucionados e Fechados<br>\nEm atendimento engloba Atribuídos e Planejados",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  DATE_FORMAT(gt.date_creation, '%d/%m %H:00') as \"Hora\",\r\n  COUNT(gt.id) as \"Total\",\r\n  SUM(CASE WHEN gt.status IN (5,6) THEN 1 ELSE 0 END) as \"Encerrado\",\r\n  SUM(CASE WHEN gt.status IN (2,3) THEN 1 ELSE 0 END) as \"Em Atendimento\",\r\n  SUM(CASE WHEN gt.status = 1 THEN 1 ELSE 0 END) as \"Novo\",\r\n  SUM(CASE WHEN gt.status = 4 THEN 1 ELSE 0 END) as \"Pendente\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.date_creation >= DATE_SUB(NOW(), INTERVAL 24 HOUR) \r\n  AND gt.is_deleted = 0\r\n  AND gg.completename LIKE '%Suporte%'  \r\nGROUP BY Hora\r\nORDER BY Hora ASC;\r\n"
    }
   ]
  },
  {
   "title": "SLA 1ª Resposta Sistemas (24 h)",
   "type": "gauge",
   "description": "Tempo médio para a primeira resposta ao ticket, nas últimas 24 horas",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  AVG(gt.takeintoaccount_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Tempo Médio\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.date_creation >= DATE_SUB(NOW(), INTERVAL 24 HOUR)\r\n  AND gg.completename LIKE '%Sistemas%'\r\n  AND gt.is_deleted = 0\r\n"
    }
   ]
  },
  {
   "title": "Tempo Médio Atendimento Sistemas (24 h)",
   "type": "gauge",
   "description": "Tempo médio de atendimento dos tickets encerrados nas últimas 24h.",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Tempo Médio\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.solvedate >= DATE_SUB(NOW(), INTERVAL 24 HOUR)\r\n  AND gg.completename LIKE '%Sistemas%'\r\n  AND gt.is_deleted = 0\r\nORDER BY \r\n  \"Tempo Médio\" DESC;\r\n"
    }
   ]
  },
  {
   "title": "Tickets por Agente Infra (24 h)",
   "type": "table",
   "description": "Filtra chamados encerrados / média tempo / por agente nas últimas 24h.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT\r\n  CONCAT(gu.firstname,' ',gu.realname) as \"Nome\",\r\n  COUNT(gt.id) as \"Total\",\r\n  COUNT(gt.solvedate) as \"Solucionados\",\r\n  AVG(NULLIF(gt.solve_delay_stat, 0) - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Média\",\r\n  gg.name as \"Setor\"\r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_tickets_users gtu ON gt.id = gtu.tickets_id\r\n  JOIN glpi_users gu ON gu.id = gtu.users_id\r\n  JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.date_creation >= DATE_SUB(NOW(), INTERVAL 24 HOUR)\r\n  AND gg.completename LIKE '%InfraEstrutura%'\r\n  AND gtu.type = 2\r\n  AND gt.is_deleted = 0\r\nGROUP BY \r\n  Nome\r\nORDER BY \r\n  Setor ASC"
    }
   ]
  },
  {
   "title": "Tickets por Agente Sistemas (24 h)",
   "type": "table",
   "description": "Filtra chamados encerrados / média tempo / por agente nas últimas 24h.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT\r\n  CONCAT(gu.firstname,' ',gu.realname) as \"Nome\",\r\n  COUNT(gt.id) as \"Total\",\r\n  COUNT(gt.solvedate) as \"Solucionados\",\r\n  AVG(NULLIF(gt.solve_delay_stat, 0) - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Média\",\r\n  gg.name as \"Setor\"\r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_tickets_users gtu ON gt.id = gtu.tickets_id\r\n  JOIN glpi_users gu ON gu.id = gtu.users_id\r\n  JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.date_creation >= DATE_SUB(NOW(), INTERVAL 24 HOUR)\r\n  AND gg.completename LIKE '%Sistemas%'\r\n  AND gtu.type = 2\r\n  AND gt.is_deleted = 0\r\nGROUP BY \r\n  Nome\r\nORDER BY \r\n  Setor ASC"
    }
   ]
  },
  {
   "title": "Tickets por Agente Suporte (24 h)",
   "type": "table",
   "description": "Filtra chamados encerrados / média tempo / por agente nas últimas 24h.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT\r\n  CONCAT(gu.firstname,' ',gu.realname) as \"Nome\",\r\n  COUNT(gt.id) as \"Total\",\r\n  COUNT(gt.solvedate) as \"Solucionados\",\r\n  AVG(NULLIF(gt.solve_delay_stat, 0) - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Média\",\r\n  gg.name as \"Setor\"\r\nFROM \r\n  glpi_tickets gt\r\n  JOIN glpi_tickets_users gtu ON gt.id = gtu.tickets_id\r\n  JOIN glpi_users gu ON gu.id = gtu.users_id\r\n  JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.date_creation >= DATE_SUB(NOW(), INTERVAL 24 HOUR)\r\n  AND gg.completename LIKE '%Suporte%'\r\n  AND gtu.type = 2\r\n  AND gt.is_deleted = 0\r\nGROUP BY \r\n  Nome\r\nORDER BY \r\n  Setor ASC"
    }
   ]
  },
  {
   "title": "SLA 1ª Resposta Suporte (24 h)",
   "type": "gauge",
   "description": "Tempo médio para a primeira resposta ao ticket, nas últimas 24 horas",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  AVG(gt.takeintoaccount_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Tempo Médio\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.date_creation >= DATE_SUB(NOW(), INTERVAL 24 HOUR)\r\n  AND gg.completename LIKE '%Suporte%'\r\n  AND gt.is_deleted = 0\r\n"
    }
   ]
  },
  {
   "title": "Tempo Médio Atendimento Suporte (24 h)",
   "type": "gauge",
   "description": "Tempo médio de atendimento dos tickets encerrados nas últimas 24h.",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "glpi_db",
     "rawSql": "SELECT \r\n  AVG(gt.solve_delay_stat - TIMESTAMPDIFF(SECOND, gt.date, gt.date_creation)) AS \"Tempo Médio\"\r\nFROM \r\n  glpi_tickets gt\r\n  LEFT JOIN glpi_groups_tickets ggt ON ggt.tickets_id = gt.id\r\n  LEFT JOIN glpi_groups gg ON ggt.groups_id = gg.id\r\nWHERE \r\n  gt.solvedate >= DATE_SUB(NOW(), INTERVAL 24 HOUR)\r\n  AND gg.completename LIKE '%Suporte%'\r\n  AND gt.is_deleted = 0\r\nORDER BY \r\n  \"Tempo Médio\" DESC;\r\n"
    }
   ]
  }
 ]
}